### 用户登录
POST {{host}}/manage/base/login
Content-Type: application/json

{
  "account": "manage",
  "password": "123456"
}

> {% client.global.set("token", response.body.data.token); %}

### 用户信息
GET {{host}}/manage/base/me
Authorization: Basic {{token}}


### 修改资料
PATCH {{host}}/manage/base/me
Authorization: Basic {{token}}
Content-Type: application/json

{
  "avatar": "",
  "remark": "备注"
}



