### 模型列表
GET {{host}}/manage/model
Authorization: Basic {{token}}

### 模型详情
GET {{host}}/manage/model/website-faq
Authorization: Basic {{token}}


### 模型页面
GET {{host}}/manage/model/news/views
Authorization: Basic {{token}}