
### 新增新闻
POST {{host}}/model/news
Authorization: Basic {{token}}

{"category":1,"title":"新闻标题","content":"新闻内容","topic":[3]}

### 更新新闻
PATCH {{host}}/model/news/1
Authorization: Basic {{token}}

{"title":"新标题"}

### 删除新闻
DELETE {{host}}/model/news/1
Authorization: Basic {{token}}


### 新闻列表
GET {{host}}/model/news
Authorization: Basic {{token}}

### 新闻列表-关联分类
GET {{host}}/model/news?with=category&fields=title,content,created_at,topic
Authorization: Basic {{token}}

### 分类列表-关联新闻
GET {{host}}/model/category?with=post
Authorization: Basic {{token}}


### 新闻详情
GET {{host}}/model/news/1
Authorization: Basic {{token}}

### 新闻详情-关联查询
GET {{host}}/model/news/1?with=category&fields=title
Authorization: Basic {{token}}

### 新闻详情-关联查询多条
GET {{host}}/model/news/1?with=category,belong_topic&fields=title
Authorization: Basic {{token}}