
### 数据列表-关联查询
GET {{host}}/model/{{model}}?with=category&fields=title
Authorization: Basic {{token}}

### 数据列表-关联查询
GET {{host}}/model/category?with=post
Authorization: Basic {{token}}


### 数据列表
GET {{host}}/model/{{model}}
Authorization: Basic {{token}}


### 数据详情
GET {{host}}/model/{{model}}/1
Authorization: Basic {{token}}

### 数据详情-关联查询
GET {{host}}/model/{{model}}/1?with=category&fields=title
Authorization: Basic {{token}}