[base]
debug = true
name = 'ZlsApp'
port = '8181'

[db]
driver = 'sqlite'
[db.mysql]
DBName = 'zls'
Host = '127.0.0.1'
Parameters = ''
Password = '666666'
Port = 3306
User = 'root'

[db.postgres]
DBName = 'default'
Host = '127.0.0.1'
Password = '666666'
Port = 5432
SSLMode = ''
User = 'default'

[db.sqlite]
Path = 'db.db'

[account]
key = "678777654a"
only = true
